// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClztg7I_HxsMxOE6ifAJsBR5NUDsWpy8Q',
    appId: '1:844154386571:web:8d288ce945e7d048947c8e',
    messagingSenderId: '844154386571',
    projectId: 'eduproj1-27715',
    authDomain: 'eduproj1-27715.firebaseapp.com',
    storageBucket: 'eduproj1-27715.appspot.com',
    measurementId: 'G-JF6G7DVPG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7oiOfmpCyS6mLS2Dn9_FRbn5G4lgYjs',
    appId: '1:844154386571:android:d80dfe54e19fa8bc947c8e',
    messagingSenderId: '844154386571',
    projectId: 'eduproj1-27715',
    storageBucket: 'eduproj1-27715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo5ee4GgJnmaQjIVfh3EiEMTq_WeEM8GM',
    appId: '1:844154386571:ios:a1ff525eecad3a16947c8e',
    messagingSenderId: '844154386571',
    projectId: 'eduproj1-27715',
    storageBucket: 'eduproj1-27715.appspot.com',
    iosClientId: '844154386571-1i2207mpbuplpmq9lif82niciq418pq7.apps.googleusercontent.com',
    iosBundleId: 'eduproj',
  );
}
